#!/usr/bin/env perl

use strict;
use warnings;

use Time::Piece;
use Getopt::Long;

GetOptions(
  'format:s' => \(my $format),
  'utc'      => \(my $utc),
);

$format //= '%Y-%m-%dT%H:%M:%S';

while (<>) {
  my $now = $utc ? gmtime : localtime;
  print $now->strftime($format) . ": $_";
}
